sudo: required
services:
  - docker
os:
  - linux

language: node_js
node_js:
  - "6"
  - "node"

before_script:
  - npm run build-image
  - npm run start-container
  - sleep 10

script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

after_script:
  - npm run stop-container
